### ISSUE TITLE
Doesn't work in the 1.26 version

### ISSUE THREAD

**Issue by M1nk-beep** [xiaoye97/VRoidXYTool#13]
![image](https://github.com/xiaoye97/VRoidXYTool/assets/149482064/17645796-6053-472c-8f27-e250093b780e)
![image](https://github.com/xiaoye97/VRoidXYTool/assets/149482064/05821b9f-34f6-428a-8da8-9a93fdf76364)
<img width="677" alt="image" src="https://github.com/xiaoye97/VRoidXYTool/assets/149482064/e37d0791-a611-44cc-8b02-60e6d3946033">

The plugin unfortunately doesn't seem to work (at least for me) in the 1.26 version even after changing **HideManagerGameObject** to **true**
I've also tried to reinstall _VroidXYT_ (Latest release) , _BepinEx_ (Latest release, not Pre-release) and _Vroid Studio_ itself to check if it was a problem with my files.

**Comment by xiaoye97** [comment]
use BepInEx_x64_5.4.22 version, not unix or x86.

**Comment by M1nk-beep** [comment]
It worked! sorry for the bother --'

**Comment by melnation-com** [comment]
This should be pinned or linked in Readme.md or something, It's almost a better install instructions.. avoids all the future "Doesn't work on 1.## version"

I knew 'Issues > Closed' has one of the best instructions.
