### ISSUE TITLE
有没有开发VRoid插件的教程啊？

### ISSUE THREAD

**Issue by lyn-rgb** [xiaoye97/VRoidXYTool#5]
非常杰出的工作。我想问下作者，如果想尝试为VRoid开发插件，请问有什么入门教程吗？谢谢~

**Comment by xiaoye97** [comment]
如果你是中国人，你可以在bilibili搜索`宵夜97`找到我的教程视频。如果你不会使用中文，那你可以在 [BepInEx](https://github.com/BepInEx/BepInEx) 查看更多信息。

**Comment by lyn-rgb** [comment]
> 如果你是中国人，你可以在bilibili搜索`宵夜97`找到我的教程视频。如果你不会使用中文，那你可以在 [BepInEx](https://github.com/BepInEx/BepInEx) 查看更多信息。

谢谢你，已经关注大佬了。

**Comment by xiaoye97** [comment]
在我的GitHub个人信息页面有qq群，不过不怎么活跃
