### ISSUE TITLE
Doesn't work in Vroidstudio v1.18.0?

### ISSUE THREAD

**Issue by zuka-26ers** [xiaoye97/VRoidXYTool#8]
I use XYTool v0.8.0 and it works in Studio v1.7.1
![image](https://user-images.githubusercontent.com/65401914/208247928-9e2dbe69-95c6-4bf4-9e58-7ab9a879a985.png)

But in v1.8.0, GUI didn't show up .
BepInEx log is as follows.

[Message:   BepInEx] BepInEx 5.4.17.0 - VRoidStudio (2022/12/14 21:50:07)
[Info   :   BepInEx] Running under Unity v2021.3.13.10386776
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.17.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Warning:   BepInEx] Skipping [VRoidXYTool 0.7.2] because a newer version exists (VRoidXYTool 0.8.0)
[Info   :   BepInEx] Loading [VRoidXYTool 0.8.0]
[Info   :VRoidXYTool] XYTool启动
[Message:   BepInEx] Chainloader startup complete

**Comment by xiaoye97** [comment]
1. Delete the XYTool of the old version 0.7.2.
2. After VRoidStudio version 1.18 is updated, you need to edit BepInEx/config/BepInEx.cfg, change `HideManagerGameObject = false` to `HideManagerGameObject = true`

**Comment by zuka-26ers** [comment]
I did exactly what you said and it solved the problem.
Thank you for your speedy and accurate response.
