### ISSUE TITLE
XYTool does not work on Mac OS?

### ISSUE THREAD

**Issue by niyavanilla** [xiaoye97/VRoidXYTool#9]
Hello! When trying to install this plugin on Mac, it does not show up in the VRoid application. Does this plugin not support Mac OS or is there a different way to install the plugins? I did the installation as follows:

**VRoid Studio > Show Package Contents > Contents > Plugins.**

I am not sure if BepInEx installed correctly as I installed it via VRoid Chinese.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/123265002/213881314-bde51737-f6ab-4d06-a117-171481a88db7.png">

**Comment by xiaoye97** [comment]
This plug-in is not applicable to MacOS because I don't have an Apple computer.
